### ISSUE TITLE
Problem with prisma generate

### ISSUE THREAD

**Issue by dannylouveton** [grdnmsz/prisma-docker#1]
Hi, i have this problem when a run "docker-compose up -d" 

` ERROR [6/6] RUN npx prisma generate`

<img width="851" alt="Capture d’écran 2022-05-27 à 15 40 10" src="https://user-images.githubusercontent.com/24830134/170710929-8dc1f096-72f8-4198-9b74-0ec42c8baaab.png">

An idea ?

**Comment by dannylouveton** [comment]
I think it's problem with node alpine and my mac m1 i change Dockerfile with node:14.16.0 and it's work
```
FROM node:14.16.0

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install
COPY . .
EXPOSE 5000

RUN npx prisma generate
CMD [ "npm", "run", "dev" ]
```

**Comment by grdnmsz** [comment]
Hey, thank you for spotting this. I should close the issue now as it's resolved
